version: '3.8'

services:
  backend:
    build: ./backend
    container_name: portify-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always

  frontend:
    build: ./frontend
    container_name: portify-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always