version: '3.8'

services:
  backend:
    build: ./backend
    container_name: portify-backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/portify
      PORT: 8000
      JWT_SECRET: secret123
    restart: always

  frontend:
    build: ./frontend
    container_name: portify-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always